/**
 * Centralized UI Strings for Internationalization (i18n)
 * This object contains all user-facing literals used in the application.
 */
import { DEFAULT_WEBSITE_NAME } from './index.js';

export const UI_STRINGS = {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save Changes',
    create: 'Create Agent',
    delete: 'Delete',
    confirmDelete: 'Are you sure?',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    info: 'Info',
  },
  header: {
    title: DEFAULT_WEBSITE_NAME,
    apiStatus: {
      checking: 'Checking API...',
      connected: 'Connected',
      disconnected: 'Disconnected',
    },
  },
  agentList: {
    title: 'Voice Agents',
    newAgent: 'New Agent',
    empty: {
      title: 'No agents yet.',
      description: 'Click "New Agent" to create your first voice agent.',
    },
    card: {
      testCall: 'Test Call',
      copyPreviewUrl: 'Copy Preview URL',
      publicPreviewEnabled: 'Public preview enabled',
      publicBadge: 'Public',
      privateBadge: 'Private',
      createdAt: (date: string): string => new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    },
  },
  emptyState: {
    title: 'Create Your First Voice Agent',
    description: 'Configure an AI voice agent with a custom personality, system prompt, and voice. Test it with a live call right in your browser.',
  },
  preview: {
    title: 'Agent Web Call Preview',
    subtitle: 'Test call quality and view live transcription',
    unavailable: 'This preview link is unavailable.',
  },
  form: {
    createTitle: 'Create New Agent',
    editTitle: 'Edit Agent',
    nameLabel: 'Agent Name',
    namePlaceholder: 'e.g. Customer Support Bot',
    voiceLabel: 'Voice',
    modelLabel: `${DEFAULT_WEBSITE_NAME} Live Model`,
    promptLabel: 'System Prompt',
    publicPreviewLabel: 'Enable public preview URL',
    promptPlaceholder: 'You are a helpful customer support agent for Acme Corp. Be friendly, professional, and concise in your responses...',
    validation: {
      requiredFields: 'Please fill in all fields',
    },
  },
  callPanel: {
    ready: 'Ready to call',
    connecting: 'Connecting...',
    connected: 'Connected',
    ended: 'Call ended',
    mute: 'Mute/Unmute',
    download: 'Download Call Audio',
    transcriptTitle: 'Live Transcript',
    transcriptEmpty: 'Transcription will appear here during the call...',
    debugTitle: 'Signaling Logs',
    debugEmpty: 'Runtime signaling logs will appear here during the call...',
    roles: {
      user: '🎤 You',
      agent: '🤖 Agent',
      system: 'System',
    },
  },
  toasts: {
    loadAgentsFailed: 'Failed to load agents — check database connection',
    agentCreated: 'Agent created successfully',
    agentUpdated: 'Agent updated successfully',
    agentDeleted: 'Agent deleted',
    callStarted: (name: string): string => `Call started with ${name}`,
    callStartFailed: (reason: string): string => `Failed to start call: ${reason}`,
    audioRecorded: 'Audio recording ready for download',
    downloadFailed: 'Failed to generate audio download file',
    connectionError: 'Connection error',
    previewUrlCopied: 'Preview URL copied',
    telephonyCreated: 'Telephony provider added',
    telephonyUpdated: 'Telephony provider updated',
    telephonyDeleted: 'Telephony provider removed',
    telephonyLoadFailed: 'Failed to load telephony providers',
    outboundCallInitiated: (phone: string): string => `Outbound call initiated to ${phone}`,
    outboundCallFailed: (reason: string): string => `Outbound call failed: ${reason}`,
  },
  sidebar: {
    agents: 'Voice Agents',
    telephony: 'Telephony',
    callHistory: 'Call History',
    campaigns: 'Campaigns',
  },
  telephony: {
    title: 'Telephony Providers',
    addProvider: 'Add Provider',
    editProvider: 'Edit Provider',
    emptyTitle: 'No telephony providers configured',
    emptyDescription: 'Add a telephony provider to enable outbound calling from your voice agents.',
    form: {
      nameLabel: 'Provider Name',
      namePlaceholder: 'e.g. My Vobiz Line',
      providerLabel: 'Service Provider',
      directionLabel: 'Call Direction',
      phoneLabel: 'Phone Number',
      phonePlaceholder: 'e.g. +919876543210',
      sipServerLabel: 'SIP Server',
      sipServerPlaceholder: 'e.g. sip.vobiz.com',
      sipUsernameLabel: 'SIP Username',
      sipUsernamePlaceholder: 'Your SIP username',
      sipPasswordLabel: 'SIP Password',
      sipPasswordPlaceholder: 'Your SIP password',
      apiKeyLabel: 'API Key',
      apiKeyPlaceholder: 'Your API key',
      apiSecretLabel: 'API Secret',
      apiSecretPlaceholder: 'Your API secret',
      accountSidLabel: 'Account SID',
      accountSidPlaceholder: 'Your Account SID',
      authTokenLabel: 'Auth Token',
      authTokenPlaceholder: 'Your Auth Token',
      webhookUrlLabel: 'Webhook URL',
      webhookUrlPlaceholder: 'https://your-server.com/webhook',
      activeLabel: 'Active',
      saveBtn: 'Save Provider',
      updateBtn: 'Update Provider',
    },
    providers: {
      vobiz: 'Vobiz',
      twilio: 'Twilio',
      plivo: 'Plivo',
    },
    directions: {
      outbound: 'Outbound',
      inbound: 'Inbound',
    },
    card: {
      active: 'Active',
      inactive: 'Inactive',
      edit: 'Edit',
      delete: 'Delete',
      testConnection: 'Test',
    },
  },
  api: {
    errors: {
      fetchAgents: 'Failed to fetch agents',
      fetchAgent: 'Failed to fetch agent',
      agentNotFound: 'Agent not found',
      createAgent: 'Failed to create agent',
      updateAgent: 'Failed to update agent',
      deleteAgent: 'Failed to delete agent',
      requiredNamePrompt: 'Name and system prompt are required',
      invalidVoice: 'Invalid voice name',
      invalidModel: 'Invalid model name',
      invalidInput: 'Invalid request input',
      genericRequestFailed: 'Request failed',
      fetchTelephony: 'Failed to fetch telephony providers',
      createTelephony: 'Failed to create telephony provider',
      updateTelephony: 'Failed to update telephony provider',
      deleteTelephony: 'Failed to delete telephony provider',
      telephonyNotFound: 'Telephony provider not found',
      noActiveProvider: 'No active outbound telephony provider found',
      outboundCallFailed: 'Failed to initiate outbound call',
      missingPhoneNumber: 'Phone number is required',
      missingProviderCreds: 'Telephony provider credentials are incomplete',
    },
    success: {
      deleteAgent: 'Agent deleted successfully',
      deleteTelephony: 'Telephony provider deleted successfully',
      outboundCallInitiated: 'Outbound call initiated successfully',
    },
  },
  signaling: {
    errors: {
      agentIdRequired: 'Agent ID is required',
      agentNotFound: 'Agent not found',
      agentNotPublic: 'This agent is private and cannot be accessed from this link.',
      geminiConnectFailed: 'Failed to connect to Gemini Live API. Check your API key and model name.',
      invalidMessageFormat: 'Invalid signaling message format',
      wsConnectTimeout: 'Signaling connection timed out',
      micAccessTimeout: 'Microphone access timed out',
      unknownMessageType: (type: string): string => `Unknown message type: ${type}`,
    },
    logs: {
      callInit: 'Initializing call',
      callRunId: (runId: string): string => `Call run ID: ${runId}`,
      startupBegin: 'Startup sequence started',
      startupComplete: (elapsedMs: number): string => `Startup sequence completed in ${elapsedMs}ms`,
      startupFailed: (elapsedMs: number): string => `Startup failed after ${elapsedMs}ms`,
      micReady: 'Microphone stream ready',
      micRequesting: 'Requesting microphone access',
      micReadyElapsed: (elapsedMs: number): string => `Microphone ready in ${elapsedMs}ms`,
      wsConnecting: 'Connecting to signaling server',
      wsOpen: 'Signaling socket connected',
      wsOpenElapsed: (elapsedMs: number): string => `Signaling socket connected in ${elapsedMs}ms`,
      wsClosed: (code: number): string => `Signaling socket closed (${code})`,
      wsError: 'Signaling socket error',
      wsTimeout: (timeoutMs: number): string => `Signaling socket open timeout after ${timeoutMs}ms`,
      sendingStart: (agentId: string): string => `Sending start-call for agent ${agentId}`,
      startSentElapsed: (elapsedMs: number): string => `start-call sent in ${elapsedMs}ms`,
      recvType: (type: string): string => `Received signaling message: ${type}`,
      inboundValidationFailed: 'Inbound signaling payload failed validation',
      inboundParseFailed: 'Received non-JSON signaling payload',
      audioRelay: (count: number): string => `Relayed ${count} audio chunks`,
      firstAudioRelayElapsed: (elapsedMs: number): string => `First audio chunk relayed in ${elapsedMs}ms`,
      firstInboundAudioElapsed: (elapsedMs: number): string => `First inbound audio received in ${elapsedMs}ms`,
      firstInboundTranscriptElapsed: (elapsedMs: number): string => `First inbound transcript in ${elapsedMs}ms`,
      firstPlaybackElapsed: (elapsedMs: number): string => `First playback started in ${elapsedMs}ms`,
      callEndCleanup: 'Cleaning up call resources',
      callEndComplete: 'Call cleanup completed',
      startCallFailed: (msg: string): string => `Start call failed: ${msg}`,
      interrupted: 'Model response interrupted',
      bargeInDetected: 'User speech detected, interrupting model playback',
      modelInactivityWarn: (ms: number): string =>
        `No model response for ${Math.round(ms / 1000)}s after last user audio`,
      callStarted: 'Call established',
      callEnded: (reason: string): string => `Call ended: ${reason}`,
      callError: (msg: string): string => `Call error: ${msg}`,
      transcriptUser: (chars: number): string => `User transcript chunk (${chars} chars)`,
      transcriptModel: (chars: number): string => `Model transcript chunk (${chars} chars)`,
      unknownType: (type: string): string => `Unhandled signaling message type: ${type}`,
      audioQueueDepth: (depth: number): string => `Audio queue depth: ${depth}`,
      audioChunkRelayedSize: (bytes: number): string => `Audio chunk relayed: ${bytes} bytes`,
    },
    status: {
      geminiClosed: 'Gemini session closed',
      userEnded: 'User ended call',
      inactivityNudge: (nudgeNum: number, maxNudges: number): string =>
        `Model silent — sending nudge ${nudgeNum}/${maxNudges}`,
      autoEndInactivity: 'Call ended automatically due to prolonged model inactivity.',
      autoEndDuration: (secs: number): string =>
        `Call ended automatically — max duration of ${secs}s reached.`,
    },
  },
};
